//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Questao_2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ASPNETDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ASPNETDBEntities object using the connection string found in the 'ASPNETDBEntities' section of the application configuration file.
        /// </summary>
        public ASPNETDBEntities() : base("name=ASPNETDBEntities", "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ASPNETDBEntities object.
        /// </summary>
        public ASPNETDBEntities(string connectionString) : base(connectionString, "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ASPNETDBEntities object.
        /// </summary>
        public ASPNETDBEntities(EntityConnection connection) : base(connection, "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Funcionario> Funcionarios
        {
            get
            {
                if ((_Funcionarios == null))
                {
                    _Funcionarios = base.CreateObjectSet<Funcionario>("Funcionarios");
                }
                return _Funcionarios;
            }
        }
        private ObjectSet<Funcionario> _Funcionarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Funcionarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFuncionarios(Funcionario funcionario)
        {
            base.AddObject("Funcionarios", funcionario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ASPNETDBModel", Name="Concursado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Concursado : Funcionario
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Concursado object.
        /// </summary>
        /// <param name="id_Funcionario">Initial value of the id_Funcionario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="dataAdmissao">Initial value of the DataAdmissao property.</param>
        /// <param name="valeRefeicao">Initial value of the ValeRefeicao property.</param>
        /// <param name="valeTransporte">Initial value of the ValeTransporte property.</param>
        /// <param name="salario">Initial value of the Salario property.</param>
        /// <param name="valorGratificacao">Initial value of the ValorGratificacao property.</param>
        public static Concursado CreateConcursado(global::System.Guid id_Funcionario, global::System.String nome, global::System.DateTime dataNascimento, global::System.DateTime dataAdmissao, global::System.Double valeRefeicao, global::System.Double valeTransporte, global::System.Double salario, global::System.Double valorGratificacao)
        {
            Concursado concursado = new Concursado();
            concursado.id_Funcionario = id_Funcionario;
            concursado.Nome = nome;
            concursado.DataNascimento = dataNascimento;
            concursado.DataAdmissao = dataAdmissao;
            concursado.ValeRefeicao = valeRefeicao;
            concursado.ValeTransporte = valeTransporte;
            concursado.Salario = salario;
            concursado.ValorGratificacao = valorGratificacao;
            return concursado;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ValorGratificacao
        {
            get
            {
                return _ValorGratificacao;
            }
            set
            {
                OnValorGratificacaoChanging(value);
                ReportPropertyChanging("ValorGratificacao");
                _ValorGratificacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValorGratificacao");
                OnValorGratificacaoChanged();
            }
        }
        private global::System.Double _ValorGratificacao;
        partial void OnValorGratificacaoChanging(global::System.Double value);
        partial void OnValorGratificacaoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ASPNETDBModel", Name="Funcionario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Terceirizado))]
    [KnownTypeAttribute(typeof(Concursado))]
    public abstract partial class Funcionario : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_Funcionario
        {
            get
            {
                return _id_Funcionario;
            }
            set
            {
                if (_id_Funcionario != value)
                {
                    Onid_FuncionarioChanging(value);
                    ReportPropertyChanging("id_Funcionario");
                    _id_Funcionario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Funcionario");
                    Onid_FuncionarioChanged();
                }
            }
        }
        private global::System.Guid _id_Funcionario;
        partial void Onid_FuncionarioChanging(global::System.Guid value);
        partial void Onid_FuncionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataAdmissao
        {
            get
            {
                return _DataAdmissao;
            }
            set
            {
                OnDataAdmissaoChanging(value);
                ReportPropertyChanging("DataAdmissao");
                _DataAdmissao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAdmissao");
                OnDataAdmissaoChanged();
            }
        }
        private global::System.DateTime _DataAdmissao;
        partial void OnDataAdmissaoChanging(global::System.DateTime value);
        partial void OnDataAdmissaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ValeRefeicao
        {
            get
            {
                return _ValeRefeicao;
            }
            set
            {
                OnValeRefeicaoChanging(value);
                ReportPropertyChanging("ValeRefeicao");
                _ValeRefeicao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValeRefeicao");
                OnValeRefeicaoChanged();
            }
        }
        private global::System.Double _ValeRefeicao;
        partial void OnValeRefeicaoChanging(global::System.Double value);
        partial void OnValeRefeicaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ValeTransporte
        {
            get
            {
                return _ValeTransporte;
            }
            set
            {
                OnValeTransporteChanging(value);
                ReportPropertyChanging("ValeTransporte");
                _ValeTransporte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValeTransporte");
                OnValeTransporteChanged();
            }
        }
        private global::System.Double _ValeTransporte;
        partial void OnValeTransporteChanging(global::System.Double value);
        partial void OnValeTransporteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Salario
        {
            get
            {
                return _Salario;
            }
            set
            {
                OnSalarioChanging(value);
                ReportPropertyChanging("Salario");
                _Salario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salario");
                OnSalarioChanged();
            }
        }
        private global::System.Double _Salario;
        partial void OnSalarioChanging(global::System.Double value);
        partial void OnSalarioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ASPNETDBModel", Name="Terceirizado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Terceirizado : Funcionario
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Terceirizado object.
        /// </summary>
        /// <param name="id_Funcionario">Initial value of the id_Funcionario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="dataAdmissao">Initial value of the DataAdmissao property.</param>
        /// <param name="valeRefeicao">Initial value of the ValeRefeicao property.</param>
        /// <param name="valeTransporte">Initial value of the ValeTransporte property.</param>
        /// <param name="salario">Initial value of the Salario property.</param>
        /// <param name="auxilioFaculdade">Initial value of the AuxilioFaculdade property.</param>
        public static Terceirizado CreateTerceirizado(global::System.Guid id_Funcionario, global::System.String nome, global::System.DateTime dataNascimento, global::System.DateTime dataAdmissao, global::System.Double valeRefeicao, global::System.Double valeTransporte, global::System.Double salario, global::System.Double auxilioFaculdade)
        {
            Terceirizado terceirizado = new Terceirizado();
            terceirizado.id_Funcionario = id_Funcionario;
            terceirizado.Nome = nome;
            terceirizado.DataNascimento = dataNascimento;
            terceirizado.DataAdmissao = dataAdmissao;
            terceirizado.ValeRefeicao = valeRefeicao;
            terceirizado.ValeTransporte = valeTransporte;
            terceirizado.Salario = salario;
            terceirizado.AuxilioFaculdade = auxilioFaculdade;
            return terceirizado;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AuxilioFaculdade
        {
            get
            {
                return _AuxilioFaculdade;
            }
            set
            {
                OnAuxilioFaculdadeChanging(value);
                ReportPropertyChanging("AuxilioFaculdade");
                _AuxilioFaculdade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuxilioFaculdade");
                OnAuxilioFaculdadeChanged();
            }
        }
        private global::System.Double _AuxilioFaculdade;
        partial void OnAuxilioFaculdadeChanging(global::System.Double value);
        partial void OnAuxilioFaculdadeChanged();

        #endregion

    
    }

    #endregion

    
}
